# Generated by Django 3.1.3 on 2020-11-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nice', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
