# Generated by Django 3.1.3 on 2020-11-16 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nice', '0005_auto_20201116_0040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
